[main]
font=JetBrains Mono:size=16

# Koda dark and light
[colors-dark]
alpha=0.95
foreground=ffffff
background=101010
cursor=101010 b0b0b0
selection-foreground=b0b0b0
selection-background=272727
regular0=101010
regular1=ff7676
regular2=a3d6a3
regular3=ffffff
regular4=b3b3b3
regular5=f4b8e4
regular6=fafafa
regular7=a5adce
bright0=50585d
bright1=ff5733
bright2=86cd82
bright3=d9ba73
bright4=ffffff
bright5=f2a4db
bright6=5abfb5
bright7=b5bfe2

[colors-light]
foreground=101010
background=faf9f5
cursor=faf9f5 6a6a6a
selection-foreground=101010
selection-background=ebebeb
regular0=ebebeb
regular1=ca0043
regular2=407f00
regular3=926200
regular4=3d3d3d
regular5=a200d1
regular6=007d7d
regular7=6a6a6a
bright0=969ba5
bright1=f30052
bright2=4f9a00
bright3=b07700
bright4=000000
bright5=c301fb
bright6=009797
bright7=101010
